### ISSUE TITLE
Fan Art navigation is not working correctly

### ISSUE THREAD

**Issue by kanarb** [UCSCLibrary/gdao-theme#10]
If you navigate to a certain letter on the fan art page (example: http://gdao2-dev.library.ucsc.edu/fan-art?letter=H) you arrive at the correct page. But if you then choose next and then previous you do not come back to the original page. The order of the envelopes is not clear and finding a specific envelope would be difficult.

**Comment by NedHenry** [comment]
I have fixed the problem with the next and previous buttons. 
You raise a good point about finding a specific envelope, though. Can you think of a neat way to allow people to find envelopes more easily? We could add an envelope-specific search box to this page, or have an index of names people could scroll through, or even just let people view more thumbnails at a time perhaps?

**Comment by kanarb** [comment]
I talked with Sue about this. She thinks it's not important enough to worry about. People can always use the main search box to find the envelopes they want.
