### ISSUE TITLE
Links to Policies and Credits in the footer are not styled correctly

### ISSUE THREAD

**Issue by kanarb** [UCSCLibrary/gdao-theme#11]
They are styled like the top nav bar rather than like footer links.

**Comment by kanarb** [comment]
I fixed this by turning rules defined like this:

```
ul#nav-collection li
```

into this:

```
#banner-bottom ul#nav-collection li
```

**Comment by NedHenry** [comment]
Woops! I fixed it too, independently, by changing the markup to match the other sections in the footer. I don't know why these links had unique formatting in the first place.
