### ISSUE TITLE
Language link not filtering correctly

### ISSUE THREAD

**Issue by kanarb** [UCSCLibrary/gdao-theme#14]
The Language link in item descriptions should filter by that language (compare http://www.gdao.org/items/show/279779 with http://gdao2-dev.library.ucsc.edu/items/show/279779).

**Comment by NedHenry** [comment]
Since we have very little non-english content, and the rest of the site does not have any multi-language support, I simply removed the "Language" field from the list of filters for now. We can add it again if this functionality is desired by anyone.
