### ISSUE TITLE
Advanced search not working

### ISSUE THREAD

**Issue by kanarb** [UCSCLibrary/gdao-theme#18]
An advanced search results in the following error:

Omeka has encountered an error
Apache_Solr_HttpTransportException
    '400' Status: Bad Request

**Comment by NedHenry** [comment]
I cannot currently replicate this problem. Have you seen this problem in the last week? I fixed a problem with advanced search a week or two ago; is this that same issue, or is there a new problem that I am currently not seeing? Cheers, thanks for reporting!

**Comment by kanarb** [comment]
I was getting the error earlier today, but it seems to be working fine now.

**Comment by NedHenry** [comment]
That's odd...I didn't think I'd done anything that would cause or fix such an error today. Let me know if you see any other advances search errors. 
In the future, I vote we replace this advanced search function with the kind the admin panel uses, which is not based on the solr index. This will give us more flexible search parameters and a built in user interface, at the cost of a slower search (which I think is fine for advanced searches).
