### ISSUE TITLE
missing fields/functionality on item pages

### ISSUE THREAD

**Issue by kanarb** [UCSCLibrary/gdao-theme#21]
Perhaps these are all intentional, but I'd like to check just to be sure. I see some changes to item pages. For example when comparing these two:

http://gdao.org/items/show/374561
http://gdao2-dev.library.ucsc.edu/items/show/374561

The new site is missing comments and tagging. Also missing are the detail fields, including the copyright statement.

**Comment by NedHenry** [comment]
This was a new bug that I accidentally added this week when I was fixing some layout issue with the primary metadata sidebar. Thanks for noticing. The missing functionality is restored.
