### ISSUE TITLE
The 'view more' links on the Media page aren't working correctly

### ISSUE THREAD

**Issue by kanarb** [UCSCLibrary/gdao-theme#26]
The 'view more' links on the Media page aren't working correctly. Whether you choose 'View More Fan Tapes', 'View More Audio Recordings', or 'View More Videos' you get a search result with all items.

**Comment by kanarb** [comment]
Ned, how do you edit shortcodes such as this one on the media page:

   [gdao_include_page slug=media]

**Comment by NedHenry** [comment]
The shortcodes are php functions that return html, which is inserted into
the page. The shortcode function "gdao_include_page" is defined in
"custom.php", and it simply includes a php file from the folder
/simple-pages/page/ by the specified name. So, the shortcode you wrote
includes the php file /simple-pages/page/media.php. Therefore, you can edit
the html that shows up in this page by editing the files in
/simple-pages/page/.

Let me know if this doesn't fully answer the question!

**Comment by kanarb** [comment]
Thanks Ned. I fixed the 'view more' links on gdao2-dev by modifying this file:

themes/gdao-theme/simple-pages/page/media.php
