### ISSUE TITLE
Item number changes

### ISSUE THREAD

**Issue by kanarb** [UCSCLibrary/gdao-theme#31]
Some items have different items numbers, which will be a problem if anyone has linked to them.

```
- http://www.gdao.org/items/show/1695773
- http://128.114.34.120/items/show/1696753

- http://www.gdao.org/items/show/1695774
- http://128.114.34.120/items/show/1696752
```

**Comment by NedHenry** [comment]
We agreed during the migration process that the URLs of contributed items would change and that we are OK with this. I believe that google analytics has confirmed that links to these items are extremely rare, and this concern seems like an edge case.
