### ISSUE TITLE
minor item show page styling problem for item type: URL

### ISSUE THREAD

**Issue by NedHenry** [UCSCLibrary/gdao-theme#33]
On items of item type URL, the "URL" field on the right sidebar is picking up the styling from the "URL" display field in the primary display area. Making the css selector slightly more specific would likely fix this problem.
http://gdao2-dev.library.ucsc.edu/items/show/100578

**Comment by kanarb** [comment]
This is fixed on gdao2-dev. Details:

At line 893 and 963 of screen.css I changed these rules:

div#primary div.url a
body#items div#primary div.url

to these:

div#fields-primary>div.url a
body#items div#fields-primary>div.url

**Comment by kanarb** [comment]
Hi Ned --
I fixed the styling on this, but now I'm thinking that the URL field shouldn't even be in the sidebar. It's just a duplicate of what's in the main content area. Also the current site doesn't have the field duplicated there. Compare:

http://128.114.34.120/items/show/100578
http://www.gdao.org/items/show/100578

**Comment by NedHenry** [comment]
Good call! This field was supposed to be ignored in the sidebar for items of type "website", but the syntax for that ignoring condition broke on the Omeka upgrade. I fixed it.
