### ISSUE TITLE
Title of newest submission is doubled

### ISSUE THREAD

**Issue by kanarb** [UCSCLibrary/gdao-theme#34]
On the home page the title of the newest submission is: Jerry GarciaJerry Garcia

**Comment by NedHenry** [comment]
I am currently seeing this on gdao.org, but not on gdao2-dev.library.ucsc.edu and also not on 128.114.34.120. I currently have no idea what that would be. I thought that gdao.org was now identical to 128.114.34.120.

**Comment by kanarb** [comment]
It looks like it's fixed.

**Comment by NedHenry** [comment]
I am not seeing it fixed. It still looks broken to me on gdao.org, and working on the other two sites. Are you seeing something different than that?

**Comment by NedHenry** [comment]
Now I'm also seeing it fixed! Still confused about this intermittent stuff. Maybe there was something confusing cache-ing going on somewhere or something.
