### ISSUE TITLE
Fanzine window is too narrow

### ISSUE THREAD

**Issue by kanarb** [UCSCLibrary/gdao-theme#35]
The fanzines are being cut off. Here's an example:

http://www.gdao.org/items/show/825874

The markup is:
`<div id="pageContainer1" class="page" data-loaded="true" data-page-number="1" style="width: 265px; height:`408px;">`

**Comment by kanarb** [comment]
I don't know if you did something to address this Ned, but it now seems to be working correctly.

**Comment by NedHenry** [comment]
I didn't do anything, but I did test it out soon enough to see the problem for a second. No idea why this fixed itself. Maybe someone is actively doing something on this domain now?
