### ISSUE TITLE
Search results pager functionality not wrking correctly

### ISSUE THREAD

**Issue by kanarb** [UCSCLibrary/gdao-theme#6]
When a search has more than one page of results the user should be able to use the page to access all pages of results. Currently using the 'Next Page' link allows the user to access the second page of results but no pages beyond that. Entering a page number to navigate to a specific page results in an error:

Omeka has encountered an error
Zend_View_Exception
    script 'admin/results.php' not found in path (/var/www/html/omeka/themes/gdao-theme/solr-search/:/var/www/html/omeka/plugins/SolrSearch/views/shared/:/var/www/html/omeka/plugins/avalonvideo/views/shared/:/var/www/html/omeka/plugins/MerrittLink/views/public/:/var/www/html/omeka/plugins/PdfEmbed/views/shared/:/var/www/html/omeka/plugins/Commenting/views/public/:/var/www/html/omeka/plugins/NeatlineTime/views/public/:/var/www/html/omeka/plugins/NeatlineTime/views/shared/:/var/www/html/omeka/plugins/DublinCoreExtended/views/shared/:/var/www/html/omeka/plugins/SimplePages/views/public/:/var/www/html/omeka/plugins/ExhibitBuilder/views/public/:/var/www/html/omeka/plugins/ExhibitBuilder/views/shared/:/var/www/html/omeka/plugins/Contribution/views/public/:/var/www/html/omeka/plugins/Contribution/views/shared/:/var/www/html/omeka/plugins/GuestUser/views/public/:/var/www/html/omeka/themes/gdao-theme/:/var/www/html/omeka/application/views/scripts/)

**Comment by NedHenry** [comment]
Fixed! At least for now. There is a little weirdness with the URLs generated by the solr-search plugin, but I added a workaround which seems to be fine for the moment.
