### ISSUE TITLE
The 'sort' function does not sort search results

### ISSUE THREAD

**Issue by kanarb** [UCSCLibrary/gdao-theme#7]
After performing a search the results should be sortable by date or relevancy. The sort widget currently does not sort the results.

**Comment by kanarb** [comment]
Note: this functionality results in an error on the current gdao.org site.

**Comment by NedHenry** [comment]
I am not sure how useful this sort box is. The date functionality is unclear (date added to collection? date created? date of the show that it is relevant to?) which leaves only one option. For now, I just deleted this box.
